//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newJhb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jhbEntities : DbContext
    {
        public jhbEntities()
            : base("name=jhbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PF> PFs { get; set; }
        public virtual DbSet<TZD> TZDs { get; set; }
        public virtual DbSet<WT> WTs { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
    }
}
