//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newJhb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TZD
    {
        public long 流水号 { get; set; }
        public string 站名 { get; set; }
        public Nullable<System.DateTime> 派单日期 { get; set; }
        public string 记录 { get; set; }
        public string 受理单位 { get; set; }
        public Nullable<long> lastEdit { get; set; }
        public string OpTrack { get; set; }
        public string ver1 { get; set; }
        public string ver2 { get; set; }
    }
}
