//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newJhb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WT
    {
        public long 问题编号 { get; set; }
        public string 站名 { get; set; }
        public string 设备名称 { get; set; }
        public string 存在问题 { get; set; }
        public Nullable<System.DateTime> 发现时间 { get; set; }
        public string 严重程度 { get; set; }
        public string 检查人 { get; set; }
        public string 整改方案 { get; set; }
        public string 受理单位 { get; set; }
        public string 天窗需求 { get; set; }
        public Nullable<bool> 销记 { get; set; }
        public Nullable<System.DateTime> 销记时间 { get; set; }
        public string 完成情况 { get; set; }
        public string 整治情况 { get; set; }
        public string 整治负责人 { get; set; }
        public string 备注 { get; set; }
        public Nullable<long> lastEdit { get; set; }
        public string OpTrack { get; set; }
        public string rev1 { get; set; }
        public string ver2 { get; set; }
    }
}
